### ISSUE TITLE
Unstable training

### ISSUE THREAD

**Issue by dingyitk159** [DopamineLcy/cocycle-reg#1]
Hello, thank you for your code. I encountered some problems while implementing the model. Could you tell me more details about the training?
I used the same preprocessing method and parameter selection as in your article, but the only difference is that I resampled the image to 1.5 * 1.5 * 1.5, and the image size was 128 * 144 * 112. However, the training process is very unstable, and registration cannot be performed correctly from the beginning of training, even causing significant deformation and deviation. Therefore, I don't know if I missed any key steps. I wonder if you have done any intensity normalization or other data normalization processing on images? Or have you done pre-train for translation networks, etc?

**Comment by DopamineLcy** [comment]
Thank you very much for your interest in our work!
Here I'm trying to give you some details that I can remind.
The intensity range of the image is very large, and maybe you need to clip to remove extremely large values of 0.5% or 1%.
I didn't do pre-training for translation networks.
I hope it's helpful to you, thank you very much again!

Best,

**Comment by dingyitk159** [comment]
Thank you very much for your answer! I will continue to try it.

**Comment by DopamineLcy** [comment]
Feel free to reopen the issue if you have any other questions.
